FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y build-essential cmake git curl && \
    apt-get clean

WORKDIR /app

COPY . .

RUN cmake -Bbuild -H. && cmake --build build --target bloomserver

EXPOSE 12345

CMD ["./build/bloomserver", "12345", "8", "1", "2"]
